// Generated by CoffeeScript 1.7.1
var NCMB, NCMB_Object, NCMBiOS;

NCMBiOS = require('com.nifty.cloud.mb.ios');

NCMB = (function() {
  function NCMB(application_key, client_key) {
    NCMBiOS.NCMBKey(application_key, client_key);
  }

  NCMB.prototype.Object = function(class_name) {
    return new NCMB_Object(class_name);
  };

  return NCMB;

})();

NCMB_Object = (function() {
  function NCMB_Object(class_name) {
    this.class_name = class_name;
    this.data = {};
  }

  NCMB_Object.prototype.set = function(key, value) {
    return this.data[key] = value;
  };

  NCMB_Object.prototype.save = function(f) {
    if (NCMBiOS.postKey(this.class_name, this.data)) {
      return f.success();
    } else {
      return f.error();
    }
  };

  return NCMB_Object;

})();

exports.App = NCMB;
